language: node_js
node_js:
  - 'stable'

cache: npm

script:
  - npm install
  - npm test
  - npm run build

deploy:
  cleanup: false
  provider: surge
  domain: https://uas-timer-tdd-ts.surge.sh
  project: ./build/

  on:
    branch: master
